# @package _global_
defaults:
    - override /datasets: d4rl

tokenizers:
    states:
      _target_: research.mtm.tokenizers.split_continuous.SplitContinuousTokenizer.create
      splits: 4
    actions:
      _target_: research.mtm.tokenizers.split_continuous.SplitContinuousTokenizer.create
      splits: 4
    returns:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create

model_config:
    n_embd: 128
    n_enc_layer: 2
    n_dec_layer: 1
    latent_dim: 16

args:
    mask_patterns: ["AUTO_MASK"]

dataset:
    use_reward: True

wandb:
    project: "rew_fix_d4rl_new_12_30"
    resume: allow
