# @package _global_
defaults:
    - override /datasets: exorl


tokenizers:
    states:
      _target_: research.mtm.tokenizers.uniform_bins.UniformBinningTokenizer.create
      num_bins: 128
    actions:
      _target_: research.mtm.tokenizers.uniform_bins.UniformBinningTokenizer.create
      num_bins: 128

wandb:
    project: "exorl_01_04"
    resume: allow
