# @package _global_
defaults:
    - override /datasets: exorl


tokenizers:
    states:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create
    actions:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create

wandb:
    project: "exorl"
    resume: allow
