dataset:
  _target_: research.mtm.datasets.sinusoid.get_datasets
  seq_steps: ???
  noise: 0.05
  train_dataset_size: 10000
  val_dataset_size: 512
model_config:
  _target_: research.mtm.models.mtm_model.MTMConfig
  norm: none
  n_embd: 512
  n_enc_layer: 2
  n_dec_layer: 1
  n_head: 4
  dropout: 0.0
  loss_keys: null
  latent_dim: 32
state_only_dataset: null
args:
  _target_: research.mtm.train.RunConfig
  seed: 0
  batch_size: 1024
  n_workers: 10
  traj_length: 4
  log_every: 100
  print_every: 1000
  eval_every: 20000
  save_every: 10000
  device: cuda
  mask_ratios:
  - 0.7
  - 0.8
  - 0.85
  - 0.9
  - 0.95
  - 1.0
  mask_patterns:
  - AUTO_MASK
  warmup_steps: 40000
  num_train_steps: 140001
  learning_rate: 0.0001
  weight_decay: 0.01
  mode_weights:
  - 0.2
  - 0.1
  - 0.7
  tsp_ratio: 1
wandb:
  project: experiments
  entity: ''
  resume: null
job_name: job
tokenizers:
  states:
    _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create
