# @package agent
_target_: agent.bc.BCAgent
name: bc
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
use_tb: ${use_tb}
hidden_dim: 1024
batch_size: 1024 # 256 for pixels
has_next_action: False
stddev_schedule: 0.2