# @package agent
_target_: agent.td3_bc.TD3BCAgent
name: td3_bc
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
alpha: 2.5
lr: 1e-4
critic_target_tau: 0.01
use_tb: ${use_tb}
hidden_dim: 1024
stddev_schedule: 0.2
stddev_clip: 0.3
nstep: 1
batch_size: 1024 # 256 for pixels
has_next_action: False
