# @package _global_
defaults:
    - override /datasets: adroit

tokenizers:
    states:
      _target_: research.mtm.tokenizers.quantile_bins.QuantileBinningTokenizer.create
      num_bins: 128
    actions:
      _target_: research.mtm.tokenizers.quantile_bins.QuantileBinningTokenizer.create
      num_bins: 128
    returns:
      _target_: research.mtm.tokenizers.quantile_bins.QuantileBinningTokenizer.create
      num_bins: 32

model_config:
    n_embd: 128
    n_enc_layer: 3
    n_dec_layer: 1
    latent_dim: 8

dataset:
    env_name: "door"

wandb:
    project: "adroit_test"
    resume: allow
