# @package _global_
defaults:
    - override /datasets: adroit

tokenizers:
    states:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create
    actions:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create
    returns:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create

state_only_dataset:
    _target_: research.mtm.datasets.adroit.get_datasets
    seq_steps: ???
    env_name: "door"
    d_name: "expert"
    train_val_split: 0.95
    use_achieved: True

dataset:
    env_name: "door"
    d_name: "expert"
    train_val_split: 0.01
    use_achieved: True

wandb:
    project: "rew_fix_d4rl_new_12_30"
    resume: allow
