# @package _global_
defaults:
    - override /datasets: adroit

tokenizers:
    states:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create
    actions:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create
    returns:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create


dataset:
    env_name: "door"

wandb:
    project: "adroit_test"
    resume: allow
