# @package _global_
defaults:
    - override /datasets: d4rl

tokenizers:
    states:
      _target_: research.mtm.tokenizers.quantile_bins.QuantileBinningTokenizer.create
      num_bins: 256
    actions:
      _target_: research.mtm.tokenizers.quantile_bins.QuantileBinningTokenizer.create
      num_bins: 256
    returns:
      _target_: research.mtm.tokenizers.quantile_bins.QuantileBinningTokenizer.create
      num_bins: 32

model_config:
    n_embd: 128
    n_enc_layer: 3
    n_dec_layer: 1
    latent_dim: 8


args:
    mask_patterns: ["AUTO_MASK", "FULL_RANDOM"]


dataset:
    use_reward: True

wandb:
    project: "rew_fix_d4rl_new_12_30"
    resume: allow
