# @package _global_
defaults:
    - override /datasets: sinusoid

tokenizers:
    states:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create

# configuration example for sinusoid notebook
args:
    batch_size: 1024
    eval_every: 500
    warmup_steps: 100
    num_train_steps: 1010
    traj_length: 16
