# @package _global_
tokenizers:
    states:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create
      normalize: False
    actions:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create
      normalize: False
    returns:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create
      normalize: False

wandb:
    project: "mlp_cont_01_01"
    resume: allow
