# @package _global_
tokenizers:
    states:
      _target_: research.mtm.tokenizers.uniform_bins.UniformBinningTokenizer.create
      num_bins: 256
    actions:
      _target_: research.mtm.tokenizers.uniform_bins.UniformBinningTokenizer.create
      num_bins: 256
    returns:
      _target_: research.mtm.tokenizers.uniform_bins.UniformBinningTokenizer.create
      num_bins: 32

wandb:
    project: "mlp_disc01_01"
    resume: allow
