# @package _global_
hydra:
    launcher:
        _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
        name: ${hydra.job.name}
        submitit_folder: ${hydra.sweep.dir}/.submitit/%j
        partition: devlab

        # nodes: 4
        # gpus_per_node: 8
        nodes: 1
        gpus_per_node: 1
        cpus_per_task: 10
        tasks_per_node: ${hydra.launcher.gpus_per_node}
        # constraint: volta32gb

        ### Debug preemption
        # timeout_min: 4
        # max_num_timeout: 1

        timeout_min: 4320
        max_num_timeout: 3

        mem_gb: 64
